# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to GitHub Packages
on:
    release:
        types: [created]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm ci
            - name: Start Docker Server
              run: docker run -d -p 9255:9255 --name litedb mastrmatt/litedb:latest
            - name: Wait for Docker Server to be ready
              run: |
                  sleep 10
            - run: npm test
            - name: Stop Docker Server
              run: docker stop litedb && docker rm litedb

    publish-gpr:
        needs: test
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: https://npm.pkg.github.com/
            - run: npm ci
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
