name: Test on Node.js

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm ci
            - name: Start Docker Server
              run: docker run -d -p 9255:9255 --name litedb mastrmatt/litedb:latest
            - name: Wait for Docker Server to be ready
              run: |
                  sleep 10
            - run: npm test
            - name: Stop Docker Server
              run: docker stop litedb && docker rm litedb
